source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-paginate'
gem 'middleman-livereload'
gem 'middleman-search_engine_sitemap'
gem 'middleman-minify-html'
gem 'redcarpet'
gem 'romanize', '~> 0.0.0'
gem 'pry'
gem 'slim'
gem 'dato'
gem 'middleman-dato'
