source 'https://rubygems.org'

gem 'middleman', '>= 4.0.0'
gem 'middleman-paginate'
gem 'middleman-livereload'
gem 'middleman-search_engine_sitemap'
gem 'middleman-minify-html'
gem 'romanize', '~> 0.0.0'
gem 'pry'
gem 'slim'
gem 'dato', '>= 0.3.11'
gem 'middleman-dato', '>= 0.7.2'
